AWSTemplateFormatVersion: 2010-09-09
Description: >-
  CF Template for LambdaSchool Project

Parameters:

  S3Bucket:
    Type: String
    Description: S3 bucket where the templates are stored

  WaitingTime:
    Type: Number
    Default: 2
    MinValue: 1
    MaxValue: 15
    Description: Time in minutes that will wait until retrying again (1 up to 15 minutes)
  
  EmailAddress:
    Type: String
    Default: ricardo@nclouds.com
    Description: Email to send notification

  RetryTimes:
    Type: Number
    Default: 3
    Description: Number of times it will retry waiting for the resources

  BudgetAmout:
    Type: Number
    Description: Budget amount that would stop all the resources.

  OwnerName:
    Type: String
    Description: An arbitrary tag name for the owner of these resources

  StackName:
    Type: String
    Description: The name of the stack to which these resources belong

Resources:

  ########## Lambda Stack Creation ##########
  LambdaStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${S3Bucket}/stepfunction/functions.yml"
      Parameters:
        BucketS3: !Ref S3Bucket
        WaitingTime: !Ref WaitingTime
        OwnerName: !Ref OwnerName
        StackName: !Ref StackName

  NotificationStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${S3Bucket}/notification/snsnotification.yml"
      Parameters:
        EmailAddress: !Ref EmailAddress
        OwnerName: !Ref OwnerName
        StackName: !Ref StackName

  StateMachineStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${S3Bucket}/stepfunction/statemachine.yml"
      Parameters:
        Cleaning: !GetAtt LambdaStack.Outputs.CleanUp
        LambdaWait: !GetAtt LambdaStack.Outputs.WaitingLambda
        LambdaNotification: !GetAtt NotificationStack.Outputs.NotificationLambda
        RetryTimes: !Ref RetryTimes
        OwnerName: !Ref OwnerName
        StackName: !Ref StackName

  ########## Budget Stack Creation ########
  BudgetStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${S3Bucket}/budget/budget.yml"
      Parameters:
        TriggerBudget: !Ref BudgetAmout
        LambdaFunction: !GetAtt StateMachineStack.Outputs.StartCleaning
        OwnerName: !Ref OwnerName
        StackName: !Ref StackName
