AWSTemplateFormatVersion: 2010-09-09
Description: >-
  CF Template for LambdaSchool Project

Parameters:

  S3Bucket:
    Type: String
    Description: S3 bucket where the templates are stored

  MaxLambdaWaitTime:
    Type: Number
    Default: 10
    AllowedValues: [5, 10, 15]
    Description: Timeout for lambda functions

  WaitingTime:
    Type: Number
    Default: 2
    Description: Time in minutes waiting
  
  RetryTimes:
    Type: Number
    Default: 3
    Description: Number of times it will retry waiting for the resources

  OwnerName:
    Type: String
    Default: ricardo@nclouds.com
    Description: An arbitrary tag name for the owner of these resources

  StackName:
    Type: String
    Description: The name of the stack to which these resources belong

  Environment:
    Type: String
    Default: dev
    AllowedValues: [ prod, staging, dev, qa ]
    Description: Environment name to append to resources names and tags

  BudgetAmout:
    Type: Number
    Description: Budget amount that would stop all the resources.

Resources:

  ########## Lambda Stack Creation ##########
  LambdaStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${S3Bucket}/stepfunction/functions.yml"
      Parameters:
        MaxLambdaWaitTime: !Ref MaxLambdaWaitTime
        WaitingTime: !Ref WaitingTime
        OwnerName: !Ref OwnerName
        StackName: !Ref StackName
        Environment: !Ref Environment

  StateMachineStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${S3Bucket}/stepfunction/statemachine.yml"
      Parameters:
        CleaningEC2: !GetAtt LambdaStack.Outputs.CleanEC2
        CleaningRDS: !GetAtt LambdaStack.Outputs.CleanRDS
        CleaningSM: !GetAtt LambdaStack.Outputs.CleanSM
        CleaningCluster: !GetAtt LambdaStack.Outputs.CleanCluster
        Checking: !GetAtt LambdaStack.Outputs.Check
        LambdaWait: !GetAtt LambdaStack.Outputs.WaitingLambda
        RetryTimes: !Ref RetryTimes
        OwnerName: !Ref OwnerName
        StackName: !Ref StackName
        Environment: !Ref Environment

  ########## Budget Stack Creation ########
  BudgetStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${S3Bucket}/budget/budget.yml"
      Parameters:
        TriggerBudget: !Ref BudgetAmout
        LambdaFunction: !GetAtt StateMachineStack.Outputs.StartCleaning
