AWSTemplateFormatVersion: 2010-09-09
Description: >-
  CF Template for LambdaSchool Project

Parameters:

  S3Bucket:
    Type: String
    Description: S3 bucket where the templates are stored (Required)

  WaitingTime:
    Type: Number
    Default: 900
    MinValue: 300
    Description: Time in seconds to wait between each retry, minimum value 300s
  
  EmailAddress:
    Type: String
    Description: Email to send notification of the process results, requires email subscription confirmation (Required)

  RetryTimes:
    Type: Number
    Default: 3
    Description: Number of times it will retry waiting for the resources

  BudgetAmout:
    Type: Number
    Description: Budget amount that would stop all the resources (Required)

  OwnerName:
    Type: String
    Description: An arbitrary tag name for the owner of these resources (Required)

  StackName:
    Type: String
    Description: The name of the stack to which these resources belong (Required)

Resources:

  ########## Lambda Stack Creation ##########
  LambdaStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${S3Bucket}/stepfunction/functions.yml"
      Parameters:
        BucketS3: !Ref S3Bucket
        OwnerName: !Ref OwnerName
        StackName: !Ref StackName

  NotificationStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${S3Bucket}/notification/snsnotification.yml"
      Parameters:
        EmailAddress: !Ref EmailAddress
        OwnerName: !Ref OwnerName
        StackName: !Ref StackName

  StateMachineStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${S3Bucket}/stepfunction/statemachine.yml"
      Parameters:
        Cleaning: !GetAtt LambdaStack.Outputs.CleanUp
        WaitingTime: !Ref WaitingTime
        LambdaNotification: !GetAtt NotificationStack.Outputs.NotificationLambda
        RetryTimes: !Ref RetryTimes
        OwnerName: !Ref OwnerName
        StackName: !Ref StackName

  ########## Budget Stack Creation ########
  BudgetStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${S3Bucket}/budget/budget.yml"
      Parameters:
        TriggerBudget: !Ref BudgetAmout
        LambdaFunction: !GetAtt StateMachineStack.Outputs.StartCleaning
        OwnerName: !Ref OwnerName
        StackName: !Ref StackName
