---

Description:
  Template in charge of creating budget

Parameters:

  TriggerBudget:
    Type: Number
    Description: Price that would activate the budget service.

  LambdaFunction:
    Type: String
    Description: Lambda function that turn off all the resources.

  OwnerName:
    Type: String
    Description: An arbitrary tag name for the owner of these resources

  StackName:
    Type: String
    Description: The name of the stack to which these resources belong

Resources:

  Topic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: Budget-Notification
      Subscription:
        - Endpoint: !Ref LambdaFunction
          Protocol: lambda
      Tags:
        - Key: Name
          Value: !Sub budget-notification-${StackName}
        - Key: OwnerName
          Value: !Ref OwnerName
        - Key: StackName
          Value: !Ref StackName

  Policy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: SnsTopicPolicy
          Effect: Allow
          Principal:
            Service: budgets.amazonaws.com
          Action: sns:Publish
          Resource: !Ref Topic
      Topics:
        - Ref: Topic

  InvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref LambdaFunction
      Principal: sns.amazonaws.com  
      SourceArn: !Ref Topic

  Budget:
    Type: AWS::Budgets::Budget
    Properties:
      Budget:
        BudgetLimit:
          Amount: !Ref TriggerBudget
          Unit: USD
        BudgetName: Trigger-Budget
        BudgetType: COST
        TimeUnit: MONTHLY
      NotificationsWithSubscribers:
        - Notification:
            NotificationType: ACTUAL
            ComparisonOperator: GREATER_THAN
            Threshold: 100
            ThresholdType: PERCENTAGE
          Subscribers:
            - Address: !Ref Topic
              SubscriptionType: SNS
