---

Description:
  Desc.

Parameters:

  TriggerBudget:
    Type: Number
    Description: Price that would activate the budget service.

  LambdaFunction:
    Type: String
    Description: Lambda function that turn off all the resources.

Resources:

  Topic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: Budget-Notification
      Subscription: 
        - Endpoint: !Ref LambdaFuncion
          Protocol: lambda

  Policy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: SnsTopicPolicy
          Effect: Allow
          Principal:
            Service: budgets.amazonaws.com
          Action: sns:Publish
          Resource: !Ref Topic
      Topics:
        - Ref: Topic
        
  Budget:
    Type: AWS::Budgets::Budget
    Properties:
      Budget: 
        BudgetLimit: 
          Amount: !Ref TriggerBudget
          Unit: USD
        BudgetName: Trigger-Budget
        BudgetType: COST
        TimeUnit: MONTHLY
      NotificationsWithSubscribers:
        - Notification:
            NotificationType: ACTUAL
            ComparisonOperator: EQUAL_TO
            Threshold: 100
            Threshold: PERCENTAGE
          Subscribers:
            - Address: !Ref Topic
              SubscriptionType: SNS

