AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Lambda Functions that are used for the state machine

Parameters:

  BucketS3:
    Type: String
    Description: S3 Bucket where Lambda clean code is hosted

  TimeOut:
    Type: Number
    Default: 900
    AllowedValues: [ 300, 600, 900]
    Description: Time out for lambdas

  WaitingTime:
    Type: Number
    Default: 2
    Description: Time in minutes waiting
  
  OwnerName:
    Type: String
    Description: An arbitrary tag name for the owner of these resources

  StackName:
    Type: String
    Description: The name of the stack to which these resources belong

Resources:

  ########## Lambda Permisions ##########
  CleanUpRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEC2FullAccess
        - arn:aws:iam::aws:policy/AmazonRDSFullAccess
        - arn:aws:iam::aws:policy/AmazonSageMakerFullAccess
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Tags:
        - Key: Name
          Value: !Sub cleanup-role-${StackName}
        - Key: OwnerName
          Value: !Ref OwnerName
        - Key: StackName
          Value: !Ref StackName
  
  ########## Lambda Code EC2 ##########
  Cleaning:
    Type: AWS::Lambda::Function
    Properties:
      Description: Lambda function that stops the resources
      Handler: lambda.lambda_handler
      Role: !GetAtt [ CleanUpRole, Arn ]
      Runtime: python3.6
      FunctionName: cleaning_lambda
      Timeout: !Ref TimeOut
      Code:
        S3Bucket: !Ref BucketS3
        S3Key: stepfunction/Code/lambda05.zip
      Tags:
        - Key: Name
          Value: !Sub cleaning-lambda-${StackName}
        - Key: OwnerName
          Value: !Ref OwnerName
        - Key: StackName
          Value: !Ref StackName

Outputs:

  ########## Clean Lambda ##########
  CleanUp:
    Description: ARN Lambda function for cleaning resources
    Value: !GetAtt Cleaning.Arn