AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Lambda Function to clean up resources

Parameters:

  MaxTime:
    Type: Number
    Default: 300
    AllowedValues: [300, 600, 900]
    Description: Timeout for lambda functions

  OwnerName:
    Type: String
    Default: ricardo
    Description: An arbitrary tag name for the owner of these resources

  StackName:
    Type: String
    Description: The name of the stack to which these resources belong

  Environment:
    Type: String
    Default: dev
    AllowedValues: [ prod, staging, dev, qa ]
    Description: Environment name to append to resources names and tags

Resources:

  ########## Lambda Permisions ##########
  CleanUpRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEC2FullAccess
        - arn:aws:iam::aws:policy/AmazonRDSFullAccess
        - arn:aws:iam::aws:policy/AmazonSageMakerFullAccess
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
  
  ########## Lambda Code ##########
  Cleaning:
    Type: AWS::Lambda::Function
    Properties:
      Description: Lambda function that stops the resources
      Handler: index.lambda_handler
      Role: !GetAtt [ CleanUpRole, Arn ]
      Runtime: python3.6
      FunctionName: CleaningResources
      Timeout: !Ref MaxTime
      Code:
        ZipFile: |
          import json
          import botocore
          import boto3
          import logging
          logger = logging.getLogger(__name__)
          logger.setLevel(logging.INFO)
          def lambda_handler(event, context):
            try:
              response = {}
              logger.info('Clean: Starting...')
              clean_up_ec2()
              clean_up_rds()
              clean_up_sm()
              logger.info('Clean: Finish...')
              response = {
                "statusCode": 200,
                "Message": "Clean Up Executed"
              }
            except Exception as e:
              logger.info('Error while executing Cleaning: '+str(e))
              response = {
                "statusCode": 500,
                "Message": str(e)
              }
              return response

          def clean_up_ec2():
            try:
              ec2 = boto3.client('ec2')
              # ----- EC2 -----------------------------
              #Filtering the instances to avoid errors...
              logger.info('Cleaning: Getting EC2 Running|Pending Instances')
              ec2_result = ec2.describe_instances(Filters=[{'Name':'instance-state-name','Values':['running','pending']}])
              instances = []
              n = 0
              for reservation in ec2_result['Reservations']:
                for instance in reservation['Instances']:
                  instances.append(instance['InstanceId'])
                  n += 1
              n = 3
              logger.info('Cleaning: Stopping '+str(n)+' EC2 Instances')
              instances = ['i-037c369dd9b7510ec', 'i-070b04d8f0f9f680c','i-0aaf513951e58821b']
              if n > 0:
                result = ec2.stop_instances(InstanceIds=instances)
            except botocore.exceptions.ClientError as e:
              logger.info('Cleaning: Error stopping ec2 Instances: '+str(err.response['Error']['Message']))
          
          def clean_up_rds():
            try:
              # ----- RDS -----------------------------
              rds = boto3.client('rds')
              logger.info('Cleaning: Getting RDS Instances')
              rds_result = rds.describe_db_instances()
              x = 0
              rds_result = {
                'DBInstances':[
                  {
                    'DBInstanceIdentifier': 'test-lambda-rc3',
                    'DBInstanceStatus': 'available',
                  }
                  ,
                  {
                    'DBInstanceIdentifier': 'test-lambda-rc5',
                    'DBInstanceStatus': 'available',
                  }
                ]
              }
              for rdsi in rds_result['DBInstances']:
                try:
                  if rdsi['DBInstanceStatus'] == 'available':
                    rds.stop_db_instance(DBInstanceIdentifier=rdsi['DBInstanceIdentifier'])
                    logger.info('Cleaning: Stopping RDS Instance: '+rdsi['DBInstanceIdentifier'])
                    x += 1
                except botocore.exceptions.ClientError as err:
                  logger.info('Cleaning: RDS Instance: '+rdsi['DBInstanceIdentifier']+" error while trying to stop it: "+str(err.response['Error']['Message']))
              
              logger.info('Stopping '+str(x)+' RDS Instances')
            except botocore.exceptions.ClientError as err:
              logger.info('Cleaning: Error stopping rds Instances: '+str(err.response['Error']['Message']))

          def clean_up_sm():
            try:
              # ------ SAGE MAKER ----------------------
              sage = boto3.client('sagemaker')
              # -- listing in service Sage Maker Instances
              logger.info('Cleaning: Getting In Service Sage Maker Instances')
              # ------ In Service Instances ------------
              sage_result_service = sage.list_notebook_instances(StatusEquals='InService')
              sage_result_service = {
                'NotebookInstances': [
                  {
                    'NotebookInstanceStatus':'InService',
                    'NotebookInstanceName': 'test-lambda-rc6',
                  }
                  ,
                  {
                    'NotebookInstanceStatus':'InService',
                    'NotebookInstanceName': 'test-lambda-rc4',
                  }
                ]
              }
              x = 0
              for n_insta in sage_result_service['NotebookInstances']:
                try:
                  sage.stop_notebook_instance(NotebookInstanceName=n_insta['NotebookInstanceName'])
                  logger.info('Cleaning: Stopping SM Instance: '+n_insta['NotebookInstanceName'])
                  x += 1
                except botocore.exceptions.ClientError as err:
                  logger.info('Cleaning: Sage Maker Instance: '+n_insta['NotebookInstanceName']+" error while trying to stop it: "+str(err.response['Error']['Message']))
              logger.info('Cleaning: Stopping '+str(x)+' Sage Maker Instances')
            except botocore.exceptions.ClientError as err:
              logger.info('Cleaning: Error stopping Sage Maker Instances: '+str(err.response['Error']['Message']))
      Tags:
        - Key: Name
          Value: !Sub clean-lambda-${Environment}
        - Key: Owner
          Value: !Ref OwnerName
        - Key: StackName
          Value: !Ref StackName
        - Key: Environment
          Value: !Ref Environment

Outputs:

  ########## Clean Outputs ##########
  CleaningLambda:
    Description: ARN Lambda function
    Value: !GetAtt Cleaning.Arn