AWSTemplateFormatVersion: 2010-09-09
Description: >-
  State machine to stop resources

Parameters:

  Cleaning:
    Type: String
    Description: Lambda function that stops the resources 

  WaitingTime:
    Type: Number
    Description: Time in seconds to wait between each retry

  LambdaNotification:
    Type: String
    Description: Lambda function that notifies when the process stops

  RetryTimes:
    Type: Number
    Default: 3
    Description: Number of times it will retry waiting for the resources

  OwnerName:
    Type: String
    Description: An arbitrary tag name for the owner of these resources

  StackName:
    Type: String
    Description: The name of the stack to which these resources belong

Resources:

  ########## State Machine Role ##########
  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - !Sub states.${AWS::Region}.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: ExecutionRolePolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource: "*"
      Tags:
        - Key: Name
          Value: !Sub execution-role-${StackName}
        - Key: OwnerName
          Value: !Ref OwnerName
        - Key: StackName
          Value: !Ref StackName
  
  ########## State Machine Definition ##########
  StateMachineDefinition:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      RoleArn: !GetAtt [ ExecutionRole, Arn ]
      DefinitionString:
        !Sub
          - |-
            {
              "Comment": "State machine that stops and checks instances status",
              "StartAt": "Params",
              "States":{
                "Params":{
                  "Type": "Pass",
                  "Result":{
                    "Iteration":1,
                    "EC2":[],
                    "CLUSTER":[],
                    "RDS":[],
                    "SM":[]
                  },
                  "Next": "Clean"
                },
                "Clean":{
                  "Type": "Task",
                  "Resource": "${CleanARN}",
                  "Next": "Decision",
                  "Retry": [{
                    "ErrorEquals": ["States.TaskFailed"],
                    "IntervalSeconds": 5,
                    "MaxAttempts": 3
                  }]
                },
                "WaitingState":{
                  "Type": "Wait",
                  "Seconds": ${WaitTime},
                  "Next": "Clean"
                },
                "SnsNotification":{
                  "Type": "Task",
                  "Resource":"${NotifyARN}",
                  "End": true,
                  "Retry": [{
                    "ErrorEquals": ["States.TaskFailed"],
                    "IntervalSeconds": 5,
                    "MaxAttempts": 3
                  }]
                },
                "Decision":{
                  "Type": "Choice",
                  "Choices":[
                    {
                      "Or":[
                        {
                          "Variable":"$.Stopped",
                          "NumericEquals": 1
                        },
                        {
                          "Variable":"$.Iteration",
                          "NumericEquals": ${NIterations}
                        }
                      ],
                      "Next":"SnsNotification"
                    }
                  ],
                  "Default":"WaitingState"
                }
              }
            }
          - CleanARN: !Ref Cleaning
            NotifyARN: !Ref LambdaNotification
            WaitTime: !Ref WaitingTime
            NIterations: !Ref RetryTimes
      Tags:
        - Key: Name
          Value: !Sub statemachine-${StackName}
        - Key: OwnerName
          Value: !Ref OwnerName
        - Key: StackName
          Value: !Ref StackName

  ########## Lambda State  Function Invoke ##########
  StepFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSStepFunctionsFullAccess
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Tags:
        - Key: Name
          Value: !Sub stepfunction-role-${StackName}
        - Key: OwnerName
          Value: !Ref OwnerName
        - Key: StackName
          Value: !Ref StackName
  
  ########## Lambda State  Function Invoke ##########
  CallStepFunction:
    Type: AWS::Lambda::Function
    Properties:
      Description: Lambda function that is in charge of calling step function
      Handler: index.lambda_handler
      Role: !GetAtt [ StepFunctionRole, Arn ]
      Runtime: python3.6
      FunctionName: CallStepFunction
      Timeout: 300
      Code:
        ZipFile:
          !Sub
            - |-
              import json
              import boto3
              import logging
              logger = logging.getLogger(__name__)
              logger.setLevel(logging.INFO)
              def lambda_handler(event, context):
                try:
                  instances = []
                  response = {}
                  logger.info('Starting Cleaning Up...')
                  client = boto3.client('stepfunctions')
                  client.start_execution(stateMachineArn='${SMArn}')
                  response = {
                    "statusCode":200,
                    "Message": "Executing Clean Up"
                  }
                  return response
                except botocore.exceptions.ClientError as e:
                  logger.info("Cleaning >> Error while executing cleaning: "+str(e.response['Error']['Message']))
                  return response
            - SMArn: !Ref StateMachineDefinition
      Tags:
        - Key: Name
          Value: !Sub callstepfunction-${StackName}
        - Key: OwnerName
          Value: !Ref OwnerName
        - Key: StackName
          Value: !Ref StackName

Outputs:
  StateMachineFunction:
    Description: The State Machine that manages lambda functions
    Value: !Ref StateMachineDefinition

  StartCleaning:
    Description: Lambda function calls state machine
    Value: !GetAtt CallStepFunction.Arn
