AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Template to create notification

Parameters:

  EmailAddress:
    Type: String
    Description: Email address to notify clean up result

  OwnerName:
    Type: String
    Default: ricardo
    Description: An arbitrary tag name for the owner of these resources

  StackName:
    Type: String
    Description: The name of the stack to which these resources belong

  Environment:
    Type: String
    Default: dev
    AllowedValues: [ prod, staging, dev, qa ]
    Description: Environment name to append to resources names and tags

Resources:

  ########## Topic ##########
  TopicNotification:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: Budget-Notification
      Subscription:
        - Endpoint: !Ref EmailAddress
          Protocol: email
      Tags:
        - Key: Name
          Value: !Sub topic-notification-${Environment}
        - Key: Owner
          Value: !Ref OwnerName
        - Key: StackName
          Value: !Ref StackName
        - Key: Environment
          Value: !Ref Environment
  
  ########## Topic Policy ##########
  PolicyNotification:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: SnsTopicPolicy
          Effect: Allow
          Principal:
            Service: budgets.amazonaws.com
          Action: sns:Publish
          Resource: !Ref TopicNotification
      Topics:
        - Ref: TopicNotification
    
    
